### ISSUE TITLE
nil panic in AzureMachinePoolMachine controller

### ISSUE THREAD

**Issue by mweibel** [kubernetes-sigs/cluster-api-provider-azure#3106]
/kind bug

**What steps did you take and what happened:**
For some reason I don't know why, the MachinePool associated to a AzureMachinePoolMachine got deleted successfully. This then lead to a panic in azuremachinepoolmachine_controller:

```
I0127 10:22:49.175830       1 controller.go:117]  "msg"="Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" "azureMachinePoolMachine"={"name":"REDACTED","namespace":"REDACTED_NS"} "controller"="azuremachinepoolmachine" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureMachinePoolMachine" "name"="REDACTED" "namespace"="REDACTED_NS" "reconcileID"="e1d83f78-048f-42d6-bbd2-945e5ef8459e"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
       panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b9a55e]
manager
goroutine 854 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x1f29fc0, 0x37afa00})
       /usr/local/go/src/runtime/panic.go:884 +0x212
sigs.k8s.io/cluster-api-provider-azure/exp/controllers.(*AzureMachinePoolMachineController).Reconcile(0xc0003e2280, {0x25916b8?, 0xc000cf8690?}, {{{0xc001726110?, 0xe?}, {0xc001726100?, 0x10?}}})
       /workspace/exp/controllers/azuremachinepoolmachine_controller.go:174 +0x8de
sigs.k8s.io/cluster-api-provider-azure/pkg/coalescing.(*reconciler).Reconcile(0xc000976a00, {0x25916b8?, 0xc000cf85d0?}, {{{0xc001726110?, 0x10?}, {0xc001726100?, 0x40dd07?}}})
       /workspace/pkg/coalescing/reconciler.go:109 +0x3ee
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2591610?, {0x25916b8?, 0xc000cf85d0?}, {{{0xc001726110?, 0x2131f40?}, {0xc001726100?, 0x4045d4?}}})
       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004cb4a0, {0x2591610, 0xc0004d5900}, {0x1fd77c0?, 0xc00161abe0?})
       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004cb4a0, {0x2591610, 0xc0004d5900})
       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:230 +0x333
```

The [code in question](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/exp/controllers/azuremachinepoolmachine_controller.go#L169..L174) does a nil pointer check but then proceeds to access a property on a possibly nil variable. 

**What did you expect to happen:**
No nil pointer.

**Comment by mboersma** [comment]
This would imply that the previous call to `infracontroller.GetOwnerMachinePool` returned `nil` for `machinePool` but *didn't* return an error. 😕

**Comment by jackfrancis** [comment]
/assign @Jont828 @mboersma 

Maybe the first step is to see how easy this is to repro? If this repros during every AzureMachinePoolMachine delete operation, I think we'd want to prioritize fixing it.
